---
output: github_document
bibliography: ref/biblio.bib
csl: ref/apa.csl
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE#,
  # collapse=TRUE,
  # fig.path = "../img/"
)
```

<!-- Este .md fue generado a partir del .Rmd homónimo. Edítese el .Rmd -->

# Programa de "Geomorfología" <br/> Licenciatura en Geografía <br/> Universidad Autónoma de Santo Domingo (UASD)
Agosto 2022 <br/>
*José Ramón Martínez Batlle, el tali*


## Básicos:

* Modalidad: presencial

* Correo: jmartinez19@uasd.edu.do

* Lugar y horario: FC-203, Lunes de 4 a 8 pm

* [Programa (vínculo recursivo)](programa-geomorfologia.md)

<!-- * [Guía para la redacción de tu manuscrito](guia-redaccion-manuscrito.md) -->

## Descripción

Comienzo con una cita, primero en su idioma original, luego traducida:

>Earth’s landscapes are sculpted by a suite of geomorphic processes that vary with position on the Earth and with time due to changes in the climate. Landscapes contain signatures of the principal active processes that we would like to learn to read [@anderson2010geomorphology].

>Los paisajes de la Tierra son esculpidos [modelados] por un conjunto de procesos geomorfológicos que cambian según la posición en el planeta y en el tiempo debido a cambios en el clima. Los paisajes contienen "firmas" [registros] del **principal proceso activo**, el cual "nos [te] interesa [para aprobar o para lo que veas]" aprender a leer [@anderson2010geomorphology].

Guarda ésto: "...el principal proceso activo...", y quédate también con esta otra cita:

>La Geomorfología, como otras ramas de la ciencia, necesita pasar de la simple descripción a la cuantificación y para ello tiene que utilizar métodos de otras áreas científicas, fundamentalmente de la Física [@gutierrez2008geomorfologia]

@tricart1956geomorphologie aseguraba que la Geomorfología debía apoyarse en el estudio de los procesos y también en la morfogénesis antrópica. No porque lo haya dicho él, sino porque la historia reciente le ha dado la razón: la geomorfología de procesos se ha convertido en la rama dominante desde mediados del siglo XX hasta la actualidad. Esta rama se preocupa más por el proceso que por la forma, lo cual la separa de la evolución de los grandes conjuntos de relieve [@gutierrez2008geomorfologia].

Dos grupos de procesos geomorfológicos convergen en la superficie del planeta [@anderson2010geomorphology]:

1. Las rocas de la superficie son movidas por procesos geofísicos profundos.

2. La atmósfera es movida por una distribución desigual de la radiación solar.

Aunque seguiré un guión de geomorfología de procesos, no olvidaré aproximaciones geomorfológicas tradicionales que, de otra manera, quedarían excluidas del programa (e.g. geomorfología litológica y evolutiva).

La geomorfología de procesos no sería posible sin el avance de los últimos siglos en matemáticas. Igualmente, sin la irrupción de la tecnología y el desarrollo de la programación en la segunda mitad del siglo XX, tampoco sería posible estudiar procesos a escalas grandes. Estas herramientas han permitido que la geomorfología dé respuestas cada vez más precisas a problemas de ciencias de la Tierra, como los riesgos de desastres.

## Evaluación

| Ítem | % de la \ nota final |
|-|-:|
| [Prácticas](#prácticas) | 40% |
| [Manuscrito (basado en datos pre-existentes)](#manuscrito) | 50% |
| [Presentación oral](#presentación-oral) | 10% |

Sí sí, lo que viste, no hay examen.

Brevemente, cada ítem a evaluar consistirá en lo siguiente (más detalles por medio de asignaciones a lo largo del curso):

### Prácticas

Aplicaciones de las siguientes técnicas a la geomorfología:

1. Sistemas de información geográfica (QGIS + GRASS GIS + R).

2. GNSS (RTKLIB).

3. Fotogrametría (OpenDroneMap + GRASS GIS).

4. Teledetección (SNAP + QGIS).

5. Práctica de campo.

6. Machine learning (R + Python)

Estas asignaciones te ayudarán a manejar herramientas (algunas reproducibles) en geomorfología. Necesitarás una PC en la cual deberás instalar los programas y lenguajes requeridos.

Orientaré con ejemplos y soluciones de forma pública en las sesiones de clases. De esta forma, las discusiones quedarán disponibles para otras personas. Cuando necesites hacer consultas, debes plantear el problema al que te enfrentas, cómo has intentado resolverlo o qué soluciones has probado. Si se trata de alguna cuestión relacionada con programación o análisis de datos, deberás facilitar **código reproducible y mensaje de error (si lo hubiere)**. Cuando escribas tus dudas, no recurras al típico "da error", puesto que no conduce a nada. En su lugar prefiere estas expresiones *"intente este procedimiento ... , dio este error, luego intenté esta solución ... pero no consigo dar con el fallo"*.

### Manuscrito

Tratará sobre un tema de geomorfología del contenido teórico (ver al final) que te resulte de interés. En general, trabajarás sobre procesos geomorfológicos en morfosistemas o elementos morfológicos específicos elegidos por ti. Algunos ejemplos concretos agrupados por temas:

#### Temas sugeridos

a. Geomorfología tectónica: deformación, ¿depósitos? (difíciles de conseguir), perfiles de ríos afectados.
    
b. Procesos fluviales (ríos y relacionados): evolución de canales, distribución de depósitos, inundaciones, abanicos aluviales, cuencas.
    
c. procesos de Vertientes: debris flows, deslizamientos, geometría de vertientes.
    
d. Procesos litorales: costas rocosas, costas no rocosas, evolución, depósitos. 
    
e. Procesos eólicas: depósitos, dunas, evolución.
    
f. Morfosistema kárstico: morfometría kárstica, procesos, depósitos, evolución.

#### Fases de desarrollo

Elaborarás tu manuscrito siguiendo estas fases:

1. Formulación del problema/pregunta(s) de investigación, siendo preceptiva la sencillez de diseño. Las preguntas de investigación a responder las diseñarás tú. Consulta al profesor para construir tus preguntas en una sesión de clase, para que las preguntas formuladas sean "respondibles" sin caer en simplismos.

2. Revisión bibliográfica. Busca fuentes en línea, pero evita abrumarte con la enorme disponibilidad de publicaciones científicas sobre geomorfología. Prefiere las publicaciones disponibles en acceso libre, y no olvides el [Sci-Hub](https://sci-hub.se).

3. Selección de metodología, incluyendo técnicas cuantitativas de forma preceptiva.

4. Recogida de datos, ya fuese un modelo digital de elevaciones (DEM) o por levantamientos en campo.

5. Análisis de datos.

6. Redacción. Volver eterna y recursivamente a 5 hasta que la redacción quede "nítida".

#### Criterios de evaluación del manuscrito

Los criterios de evaluación que usaré para el manuscrito son:

1. Cumplimiento de los requisitos exigidos por el [Anuario de Investigaciones Científicas](https://www.uasd.edu.do/index.php/publicaciones-cientificas) de la UASD.

2. Redacción coherente y concisa.

3. Resultados, con el debido apoyo estadístico y gráfico, que respondan a las preguntas formuladas.

4. Concisa extracción de conclusiones.

Para preparar tu manuscrito, sigue las normas para autores/as del [Anuario de Investigaciones Científicas de la UASD](docs/instrucciones-para-autores-anuario-investigaciones-cientificas-UASD.pdf). Fungiré como editor ficticio de la revista, e incluso como revisor (*reviewer&nbsp;#2*).

* Como verás, el manuscrito requiere los siguientes ítems:
    * Título.
    * Nombre de autor/a.
    * Resumen y palabras clave.
    * *Abstract* y *keywords* (optativo).
    * Introducción
    * Metodología.
    * Resultados.
    * Discusión.
    * Agradecimientos (optativo).
    * Referencias citadas.
    * *Script* reproducible
    * Declaración de cumplimientos legales y de no conflictos de intereses (optativo).
    * Otros requerimientos (ponle atención también a esta parte en las [normas](docs/instrucciones-para-autores-anuario-investigaciones-cientificas-UASD.pdf)).

* Toma en consideración lo siguiente:

    * No impartiré lecciones sobre redacción ni sobre procesadores de texto, por lo que te recomiendo consultar material tanto vía web como en el economato para mejorar dichas capacidades.

    * El plagio y la falsificación de datos supondrán la reprobación inmediata de la asignatura.

    * Te recomiendo consultar [uno o varios artículos de cualquier número del Anuario](https://www.uasd.edu.do/index.php/publicaciones-cientificas), para que te familiarices con el estilo de redacción.

### Presentación oral

Dispondrás de 15 minutos para presentar oralmente tu trabajo al final del semestre. Valoraré el dominio que muestres del tema y de tus resultados.

## Contenido teórico de la asignatura

* Tema 1. Epistemología, conceptos, bases geológicas e introducción a los procesos de la superficie terrestre. Páginas en @gutierrez2008geomorfologia: 1 a 45, ambas inclusive. Páginas @anderson2010geomorphology: 1 a 15, ambas inclusive.

* Tema 2. Tiempo en geomorfología. Técnicas de datación relativas, técnicas de datación absoluta. En @gutierrez2008geomorfologia: páginas 52 a 54, ambas inclusive. En @anderson2010geomorphology: capítulo 6.

* Tema 3. Meteorización y formas resultantes. En @gutierrez2008geomorfologia: capítulo 5. En @anderson2010geomorphology: capítulo 7.

* Tema 4. Procesos fluviales. Conceptos básicos de hidrología e hidráulica fluvial, procesos fluviales. Formas y depósitos fluviales (aluvionamientos, terrazas, diques, barras, etc.), abanicos. En @gutierrez2008geomorfologia: capítulos 8 y 9.

* Tema 5. Procesos de laderas y movimientos en masa. Laderas, balance de masa, y otros. Procesos elementales: rainsplash, solifluxión, procesos biogeomorfológicos, y otros. Movimientos de masa (procesos gravitacionales/de laderas): principios físicos, tipologías (caída, deslizamiento, flujo, reptación), debris flow, modelos de laderas/morfometría. En @gutierrez2008geomorfologia: capítulo 7.

* Tema 6. Procesos litorales. Aguas marinas litorales, productos característicos de la dinámica litoral. Básicos: conceptos, dinámica de las aguas litorales (oleajes, mareas, corrientes). Zonas, subzonas, elementos del litoral, productos morfológicos (costas arenosas, costas rocosas). En @gutierrez2008geomorfologia: capítulo 11.

* Tema 7. Geomorfología kárstica. En @gutierrez2008geomorfologia: capítulo 6.

* Tema 8. Geomorfología climática: medios áridos y semi-áridos, dominio tropical. En @gutierrez2008geomorfologia: capítulos 12, 16, 17 y 18.

## Referencias

