---
title: "Práctica 99. Introducción de tu manuscrito."
author: José Ramón Martínez Batlle
date: 05-09-2022
output: github_document
bibliography: ../ref/biblio.bib
csl: ../ref/apa.csl
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, cache=F)
```

# Fecha de entrega

- 16 de septiembre, 2022

# ¿Qué contiene una introducción?

La introducción responde a la pregunta ¿Por qué? No sueles justificar una acción, un deseo o un estudio con una simple oración. Das contexto y, cuando ya has planteado la imagen global del tema en cuestión (e.g. avances realizados hasta ahora, vacíos existentes), entonces haces el planteamiento del problema. Normalmente, un problema por resolver es algo muy global (piensa en él como el tradicional objetivo general), por lo que te enfocas en preguntas de investigación específicas (piensa en éstas como los tradicionales objetivos específicos).

Por el mismo razonamiento anterior, normalmente verás que en tutoriales sobre redacción, se recomienda que en el último párrafo de la introducción formules tus preguntas de investigación o tus objetivos; si te es posible, también formula hipótesis para cada pregunta. Considera una hipótesis como una posible respuesta a cada pregunta, pero no te esfuerces en formular "la hipótesis correcta"; formula una posible respuesta a cada pregunta de acuerdo a lo que entiendas lógico.

Algunas referencias generales sobre cómo redactar la introducción que considero útiles son estas:
 
  - [Pautas para elaborar una introducción en español](http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S0120-53072008000100001). 
  
  - [Estas pautas, en inglés](https://www.editage.com/insights/4-step-approach-to-writing-the-introduction-section-of-a-research-paper). Puedes usar el traductor [DeepL](https://www.deepl.com/translator), porque produce frases más naturales.


# ¿Cómo proceder?

Mi recomendación es que sigas este flujo:

  1. Lee los temas de [esta lista](../programa-geomorfologia.md#temas-sugeridos) y elige uno. Si tienes algún tema no incluido en la lista, lo discutimos.
  
  2. Esta es la parte más importante: **revisa artículos disponibles sobre el tema** (busca en Google Scholar, por ejemplo), pero no te pierdas en el océano de fuentes que encontrarás. Pregúntame y te dirijo oportunamente. A medida que leas fuentes, haz lo siguiente:
    - Lleva cuenta de los artículos revisados. Los usarás en tu introducción y los tendrás que referir apropiadamente. Usa alguna herramienta de apoyo, como Zotero o las propias herramientas incorporadas en tu procesador de texto elegido.
    - Concéntrate en el resumen del artículo y, si acaso, lee la última parte de la introducción. Si algún método empleado te pareciera interesante, mira el detalle en la sección de metodología del artículo.
    - Toma nota de las fuentes que encuentres e identifica su aportación más relevante (esto es lo que antes se hacía por medio de "fichas").
    - Identifica los problemas no resueltos que se destacan en las más recientes publicaciones.
    - Evalúa la posibilidad de aplicar lo leído al caso dominicano.
  
  3. A partir de lo leido, redacta varias preguntas de investigación candidatas.
  
  4. Discútelas conmigo. Elegiremos las idóneas.
  
  5. Redacta tu introducción siguiendo el esquema de la [sección anterior](#que-contiene-una-introduccion)


# Referencias
